@startuml User_container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons

!include DEVICONS/postgresql.puml
!include DEVICONS/redis.puml

Person(client, "Client", "Site/Mobile")
Container(loadBalancer, "Load Balancer", "Nginx", "Uses round robin", $sprite="nginx")
Container(media, "S3 Storage", "Ceph/Minio", "Store images by image_url")
Container(geoService, "Geo Service", "Go", "Store and handle geo marks")
Container(reactions, "Reactions Service", "Go", "Store and handle comments and likes")
Container(postService, "Post Service", "Go", "Store and handle posts")
ContainerQueue(messageQueue, "Events queue", "Kafka", "Message queue for events by post updates")

Container_Boundary(userServiceGroup, "User Service") {
    Container(userService, "User Service", "Go", "Store and handle users", $tags="webApp")
    ContainerDb(userDb, "User database", "PgSQL", "Stores users, subscribes", $tags="db", $sprite="postgresql")
    ContainerDb(userCache, "User cache", "Redis", "Stores popular users", $tags="db", $sprite="redis")
}

Rel(userService, userDb, "Read/write users/subscribes")
Rel(userService, userCache, "Cache popular users")

Rel(client, loadBalancer, "Request", "REST")
Rel(loadBalancer, postService, "CRUD post, search", "REST")
Rel(loadBalancer, userService, "CRUD users, subscribes", "REST")
Rel(loadBalancer, reactions, "CRUD likes/comments", "REST")
Rel(loadBalancer, media, "CRUD media", "REST")

Rel(postService, geoService, "Get geo info")
Rel(userService, geoService, "Get geo info")
Rel(postService, messageQueue, "Publishes events for adding/removing a post")
Rel(reactions, messageQueue, "Subscribes on events for adding/removing a post")
Rel(postService, media, "Notify about changes")
@enduml