@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/nginx.puml
!include DEVICONS/postgresql.puml

Person(client, "Client", "Site/Mobile")
Container_Ext(loadBalancer, "Load Balancer", "Nginx", "Routes incoming requests")
System_Ext(postSystem, "Post System", "Notifies about new media")

System_Boundary(mediaServiceGroup, "Media Service") {
    Container(mediaStorage, "Media Storage", "S3-like (Ceph/MinIO)", "Stores images/videos", $sprite="s3")
    ContainerDb(mediaDb, "Media database", "PgSQL", "Tracks image URLs and states", $tags="db", $sprite="postgresql")
}

Rel(client, loadBalancer, "Upload/download media", "REST")
Rel(loadBalancer, mediaStorage, "Forward requests", "REST")

Rel(mediaStorage, mediaDb, "Read/write media metadata")

Rel(postSystem, mediaStorage, "Notify about new/updated media")
@enduml